version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: docker/api/Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./db:/app/db
      - ./logs:/app/logs
      - ./src:/app/src
    environment:
      - SQLITE_DB_PATH=/app/db/syllabus.db
      - DEBUG_MODE=true
      - LOG_LEVEL=debug
      - MAX_WORKERS=4
      - RELOAD_MODE=true
      - API_PREFIX=/api/v1
      - CORS_ORIGINS=["http://localhost:3000"]
      - CORS_ALLOW_CREDENTIALS=true
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped 