version: '3.8'

services:
  db:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5433:5432"
    env_file:
      - ../.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - api-network
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local

networks:
  api-network:
    name: api-network
    driver: bridge 